### ISSUE TITLE
Configurations / Demo / TODOs

### ISSUE THREAD

**Issue by billheaton-q2** [q2ebanking/ember-unified-select#2]
Todo list for adding configurable behaviors, e.g. use Sass, use ember-responsive breakpoints, etc.

- [x] Rename component to `unified-select` (completed on ah/production-cleanup branch) - AH
~~-[ ] Use getOwner to looking config:environment for addon to utilize consuming app config values~~
~~- [ ] Setup example dummy app config for opt-in use of sass~~
~~- [ ] Setup config for defining breakpoints, e.g. defaults or map to consuming app breakpoint names - BH~~
- [x] Cleanup references to prior code -AH
- [x] Create substitute for icons and their usage -AH
- [x] Setup demo on github pages showing default styles -AH

**Comment by pixelhandler** [comment]
@abdulmhamid @sharpshark28 I noticed some classnames that use `mdl-` which is based on the use of material design light. Perhaps we need to remove these?

- Search results... https://github.com/q2ebanking/ember-unified-select/search?utf8=%E2%9C%93&q=mdl-textfield__input&type=

**Comment by abdulmhamid** [comment]
@pixelhandler Yes, the goal is to remove these.

**Comment by joe-wroten-q2** [comment]
@pixelhandler @abdulmhamid  If these got split up into separate issues I'd be happy to handle a few of them. Right now it's a long list of unrelated items.

**Comment by pixelhandler** [comment]
@sharpshark28  this is just a meta issue as a list of TODOs, feel free to make an issue for any one or more of the listed items :)

**Comment by abdulmhamid** [comment]
@pixelhandler @sharpshark28 I just pushed several code changes to my running cleanup branch (`ah/production-cleanup`).  Among those changes were the component rename and removal of `mdl` references. I am still working to make it generic enough for the general public and I think the next important challenge is to begin inheriting config values from the consuming app.  I have some ideas around defaults but I would like to get this solved before making other major changes.

Note: I do not plan on merging the cleanup branch in its current state; it includes a dummy approach for style inheritance that I plan to update.

**Comment by pixelhandler** [comment]
@sharpshark28 perhaps take at look at @abdulmhamid branch for `ah/production-cleanup` I think we need that before cutting a 1.0 release

**Comment by hergaiety** [comment]
@abdulmhamid would be happy to review if there was a PR. Is it ready for that step?

**Comment by pixelhandler** [comment]
Would be cool to try out Ember CLI Addon Docs too,

- https://ember-learn.github.io/ember-cli-addon-docs/latest/
- https://medium.com/build-addepar/ember-cli-addon-docs-shared-documentation-for-the-ember-ecosystem-6f29aa0cee87

**Comment by abdulmhamid** [comment]
After some thought, I'm removing the `ember-responsive` dependency.  I'm leaving the modal style in place but it'll be an opt-in property on the component.  This way, we can keep the component dumb and this should remove the need for additional configs.  I'll push the related updates soon @pixelhandler @sharpshark28 .

**Comment by pixelhandler** [comment]
@abdulmhamid Yeah that makes sense, one less dependency is a good idea :+1:

**Comment by abdulmhamid** [comment]
The last tasks were completed or deemed unnecessary with https://github.com/q2ebanking/ember-unified-select/pull/7.
